spring:
  datasource:
    url: "jdbc:hsqldb:mem:pum"
    username: "sa"
    password:
#    url: "jdbc:hsqldb:hsql://localhost/pum"
#    username: "server"
#    password: "UnixOneLove"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    root: info
    sql: info