networks:
  connection:
    port: 3344
    timeout: 3000
    single: true
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  profiles:
    include:
      - dev
      - test
    active: dev