spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:hsql://localhost/repository #conceptually, the publisher has an own database to store credentials about publishers
    username: "sa"
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: embedded
  application:
    name: repository
  kafka:
    bootstrap-servers: petos.project.su:9092
    properties:
      schema.registry.url: "http://petos.project.su:8081"
    producer:
      client-id: "first"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    consumer:
      group-id: "first"
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
logging:
  level:
    sql: trace
    org.petos.pum.repository.controller.KafkaRepositoryController: trace
server:
  port: 8081
  address: localhost
storage:
  root:
    path: /home/Paval/Public/dum-server/storage